name: CPPLint Check

on: [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --recursive --extensions=cpp,h src/

